### ISSUE TITLE
unclear on how database will work with new android applications

### ISSUE THREAD

**Issue by Arpi-Yang** [CSC207-UofT/course-project-0xta1l#108]
right now, the way the database class methods work is by establishing a connection with a local SQLite database. the issue is that this connection process requires the specific filepath of the database. While this works on my local device because I can find and specify the filepath of my sqlite folder, im unclear on how to translate this to other devices.

**Comment by justinzzy-code** [comment]
Maybe you can try hosing the SQL for free on https://somee.com/default.aspx

And query it following this guide? 
https://docs.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-sql-server?view=sql-server-ver15
