### ISSUE TITLE
Requesting Recipes from different points of commandtree should be restricted?

### ISSUE THREAD

**Issue by miekoyao** [CSC207-UofT/course-project-0xta1l#96]
Should users be restricted to viewing the full versions of recipes only from the list of previews they just viewed (eg. from a specific genre, or from just their saved recipes)? Or is this a bug we can push to phase2?

**Comment by miekoyao** [comment]
currently, because all UserRequestRecipeView calls just use the All genre, any recipe can be requested at any time

**Comment by makayladuffus** [comment]
I think this is a bug we can push to phase 2, but I think they should be able to view the full recipe anytime they encounter a list of recipe previews. For example, when they select a genre and they are met with the recipe previews, I think from there they should be given the option to view the recipe and then maybe an additional view of the full recipe details. Also, I think at both of these steps(viewing the preview and full), we should offer the ability to save the recipe.
